### ISSUE TITLE
Bläddring i färgmarkeringar trasigt

### ISSUE THREAD

**Issue by arildm** [spraakbanken/strix-frontend#12]
TypeError: "answer.highlight is undefined"

**Comment by arildm** [comment]
Får inte det felmeddelandet. Däremot får jag "TypeError: Cannot read property '0' of undefined" på labbet. På master får jag inget felmeddelande, men när jag stegar bakåt hamnar jag alltid på första markeringen.

**Comment by arildm** [comment]
Är `/annotation_lookup` i backenden trasig?

[current_position=7 forward=true](https://ws.spraakbanken.gu.se/ws/strixlabb/annotation_lookup/wikipedia/319943645159?text_query_field=pos&text_query=NN&size=1&current_position=7&forward=true): 14
[current_position=14 forward=true](https://ws.spraakbanken.gu.se/ws/strixlabb/annotation_lookup/wikipedia/319943645159?text_query_field=pos&text_query=NN&size=1&current_position=14&forward=true): 19
[current_position=19 forward=false](https://ws.spraakbanken.gu.se/ws/strixlabb/annotation_lookup/wikipedia/319943645159?text_query_field=pos&text_query=NN&size=1&current_position=19&forward=false): 2 (borde väl vara 14)

**Comment by majsan** [comment]
Absolut, det stämmer inte alls.

**Comment by majsan** [comment]
Fixat (i koden).
