### ISSUE TITLE
Videovisningen för ivip-demo fungerar inte som utloggad

### ISSUE THREAD

**Issue by majsan** [spraakbanken/strix-frontend#14]
Anledningen är att det är hårdkodat att videofilerna ska hämtas via korpusen `ivip`, som är låst.

Här är ett exempel på en av videofilerna i `ivip-demo`, som fungerar bra att hämta utan auth:

https://ws.spraakbanken.gu.se/ws/strixlabb/resource/ivip-demo/Testkorpus/Sverige/Goteborg/Stadsteatern2/GBG2_STA_RL_018.m4v

**Comment by arildm** [comment]
Fixas i b631170
