### ISSUE TITLE
Nya inställningar för attribut

### ISSUE THREAD

**Issue by majsan** [spraakbanken/strix-frontend#3]
Vid anrop till `/config`. Tidigare så har attribut haft inställningarna `enabled` och `ignore`. Det har ersatts helt av `searchable` (skickas alltid) och `visible` (default: true). Om attributet varken är `searchable` eller `visible` så skickas det inte till frontenden.

Finns dokumenterat på: https://ws.spraakbanken.gu.se/ws/strixlabb/test/

Exempel:

        {
          "name": "topicid",
          "searchable": false,
          "translation_name": {
            "eng": "topic ID",
            "swe": "ämnes-ID"
          }
        }

På ett textattribut betyder det att man inte kan använda attributet i `text_filter`. Attributet följer inte heller med i `/aggs`-anropet.

På ett ordattribut eller strukturellt attribut så betyder det att man inte kan söka på det i `/annotation_lookup` m.h.a. `text_query_field`.

Inget attribut har `visible: false` än så länge.

**Comment by arildm** [comment]
Liite osäker på hur inställningarna används i frontenden, men jag tycker det ser ut som att de bara avgör om ett attribut syns i högra sidofältet när ett dokument är öppnat. Jag tror #6 fixar det.

**Comment by majsan** [comment]
`searchable` fanns inte innan och betyder att attributet ska kunna färgmarkeras, `visible` avgör om det ska synas i högra sidofältet. 

Det är oklart varför vi hade både `enabled` och `ignore` tidigare.
