### ISSUE TITLE
Platt design eller inte?

### ISSUE THREAD

**Issue by jroxendal** [spraakbanken/strix-frontend#7]
Sök i dokumentet-labeln och select-elementen (färgmarkera:) borde harmonisera visuellt, just nu är det värsta fajten. jag tror det är selectelementen som behöver bli plattare och ha samma grå som det ovan. 

<img width="473" alt="screenshot 2018-08-29 14 06 32" src="https://user-images.githubusercontent.com/473994/44793011-cac1ad00-ab94-11e8-9be3-b552383c765d.png">

**Comment by jroxendal** [comment]
eller en bakgrundsgradient bakom sök i dok. sen vet jag inte varför select-grejerna har två pilar? nåväl.

**Comment by arildm** [comment]
1713f6b
